name: rotating_shining_card
description: A Flutter widget that displays a 3D rotating card with a shining effect, customizable and interactive.
version: 0.1.0
homepage: https://github.com/hassan-zafar/360_rotating_shining_card

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

# flutter:
  # Add any assets or fonts if required in the future.
